services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    networks:
      - servers
    depends_on:
      - server1
      - server2
      - server3
      - balancer

  balancer:
    command:
      [
        'lb',
        '--trace=true',
        '--rate-limit=true',
        '--rate-limit-requests=1000',
        '--rate-limit-window=1m',
        '--cache=true',
        '--cache-ttl=5m',
      ]
